#!/usr/bin/env python3
"""
Adds a second captcha challenge: a no-JS "slider" alongside the existing
text challenge. The slider shows 5 points, each labeled with a random
number 1-99 (shuffled, not in order), and a prompt "Move the slider to
N". The visitor picks the point matching N by clicking it (there is no
live drag handle without JS; a click is the no-JS equivalent of
dragging the slider to that point). Both the text answer and the slider
pick must be correct for the post to go through.

This replaces inc/captcha/kaptcha/entrypoint.php's widget entirely with
a single iframe whose one HTTP request (?mode=widget) generates BOTH
challenges together and returns one HTML document containing both.

OLD_ENTRYPOINT below is the exact content pulled directly from this
server (via `cat`) on 2026-09-02.

All PHP/CSS content below is built from string-per-line lists (each
line as its own quoted string, joined with \n) rather than one big
triple-quoted block, and every tab is written as the two-character
escape \t rather than a literal tab byte -- both specifically so that
pasting this script into an SSH terminal via `cat > file << EOF` can't
trigger shell tab-completion (which happens when a heredoc line starts
with a literal tab) or get cut off by a single very long line.

Run:
    python3 add_slider_challenge.py

Idempotent: if a target file already contains the new content, that
file is skipped. inc/captcha/kaptcha/entrypoint.php is matched and
replaced as a whole; post.php and stylesheets/style.css use small text
patches.
"""
import sys

SITE_ROOT = "/home/maya"

OLD_ENTRYPOINT = "\n".join([
    "<?php",
    "// Own GD-based text captcha, styled after the \"Kaptcha\" reference screenshot:",
    "// per-character randomized font, size, weight, style, case, and rotation",
    "// on a noisy, randomized-color background.",
    "",
    "$store_dir = __DIR__ . '/../../../tmp/kaptcha/';",
    "if (!is_dir($store_dir)) {",
    "\tmkdir($store_dir, 0700, true);",
    "}",
    "",
    "// Font variants, tagged by family + weight so we can pick weight",
    "// explicitly per character (independent from family/style choice).",
    "define('KAPTCHA_FONTS', [",
    "\t['file' => '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',            'weight' => 'regular'],",
    "\t['file' => '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf',       'weight' => 'bold'],",
    "\t['file' => '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf',        'weight' => 'regular'],",
    "\t['file' => '/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf',   'weight' => 'bold'],",
    "\t['file' => '/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf',           'weight' => 'regular'],",
    "\t['file' => '/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf',      'weight' => 'bold'],",
    "]);",
    "",
    "function kaptcha_store($store_dir, $cookie, $target) {",
    "\t$path = $store_dir . preg_replace('/[^a-f0-9]/', '', $cookie) . '.json';",
    "\tfile_put_contents($path, json_encode(['target' => $target, 'ts' => time()]));",
    "}",
    "",
    "/**",
    " * Merges $fields into the existing stored record for $cookie (creating",
    " * one with the current timestamp if none exists yet), without touching",
    " * fields not present in $fields. Used to attach the slider challenge",
    " * (numbers/target/selection) to the same record as the text challenge,",
    " * keyed by the same kaptcha_cookie, instead of needing a second cookie.",
    " */",
    "function kaptcha_store_merge($store_dir, $cookie, $fields) {",
    "\t$path = $store_dir . preg_replace('/[^a-f0-9]/', '', $cookie) . '.json';",
    "\t$data = file_exists($path) ? (json_decode(file_get_contents($path), true) ?: []) : [];",
    "\tif (!isset($data['ts'])) $data['ts'] = time();",
    "\t$data = array_merge($data, $fields);",
    "\tfile_put_contents($path, json_encode($data));",
    "\treturn $data;",
    "}",
    "",
    "function kaptcha_fetch($store_dir, $cookie, $consume = true) {",
    "\t$path = $store_dir . preg_replace('/[^a-f0-9]/', '', $cookie) . '.json';",
    "\tif (!file_exists($path)) return null;",
    "\t$data = json_decode(file_get_contents($path), true);",
    "\tif ($consume) unlink($path);",
    "\treturn $data;",
    "}",
    "",
    "function kaptcha_cleanup($store_dir) {",
    "\tif (mt_rand(0, 50) !== 0) return;",
    "\tforeach (glob($store_dir . '*.json') as $f) {",
    "\t\t$data = json_decode(file_get_contents($f), true);",
    "\t\tif ($data && time() - $data['ts'] > 300) unlink($f);",
    "\t}",
    "}",
    "",
    "/**",
    " * Verify a kaptcha answer directly (used from post.php without an HTTP round-trip).",
    " * $consume controls whether the stored answer is deleted after this check —",
    " * pass false for a non-destructive \"peek\" (e.g. the widget's own [Check] button),",
    " * and leave it true for the real check that happens at post time.",
    " */",
    "function kaptcha_check_direct($store_dir, $cookie, $text, $consume = true) {",
    "\t$data = kaptcha_fetch($store_dir, $cookie, $consume);",
    "\tif (!$data) return false;",
    "\tif (time() - $data['ts'] > 300) return false;",
    "\t// case-insensitive: display randomizes case per character, but the",
    "\t// underlying answer is compared case-insensitively for usability",
    "\treturn strtolower($data['target']) === strtolower(trim($text));",
    "}",
    "",
    "/**",
    " * Verify the slider challenge: was the point the visitor picked",
    " * (slider_selected, set by the mode=slider_set click) the same point",
    " * the prompt asked for (slider_target)? Both live in the same stored",
    " * record as the text challenge, keyed by the same cookie, so this does",
    " * NOT consume/delete the record on its own — the text check",
    " * (kaptcha_check_direct) already owns that, and post.php calls this",
    " * first with $consume = false, then calls the text check to actually",
    " * consume the record. If only the slider challenge is in use for a",
    " * given call site, pass $consume = true here instead.",
    " */",
    "function kaptcha_slider_check_direct($store_dir, $cookie, $consume = false) {",
    "\t$data = kaptcha_fetch($store_dir, $cookie, $consume);",
    "\tif (!$data) return false;",
    "\tif (time() - $data['ts'] > 300) return false;",
    "\tif (!isset($data['slider_target'], $data['slider_selected'])) return false;",
    "\treturn (int)$data['slider_target'] === (int)$data['slider_selected'];",
    "}",
    "",
    "function kaptcha_random_text($length = 4) {",
    "\t// avoid ambiguous chars (0/O, 1/l/I)",
    "\t$charset = 'abcdefghjkmnpqrstuvwxyz23456789';",
    "\t$text = '';",
    "\tfor ($i = 0; $i < $length; $i++) {",
    "\t\t$text .= $charset[random_int(0, strlen($charset) - 1)];",
    "\t}",
    "\treturn $text;",
    "}",
    "",
    "/**",
    " * Generates the slider challenge: 5 points, each labeled with a random",
    " * number 1-99 (deliberately NOT in ascending/sorted order — shuffled,",
    " * so the visitor can't just guess \"leftmost is smallest\"), plus which",
    " * of the 5 points (1-indexed) is the correct one to pick.",
    " *",
    " * @return array{numbers: int[5], target: int} target is 1-5, an index",
    " *         into numbers.",
    " */",
    "function kaptcha_slider_generate() {",
    "\t$numbers = [];",
    "\t// keep the 5 numbers distinct so the prompt is unambiguous",
    "\twhile (count($numbers) < 5) {",
    "\t\t$n = random_int(1, 99);",
    "\t\tif (!in_array($n, $numbers, true)) {",
    "\t\t\t$numbers[] = $n;",
    "\t\t}",
    "\t}",
    "\tshuffle($numbers);",
    "\t$target = random_int(1, 5);",
    "\treturn ['numbers' => $numbers, 'target' => $target];",
    "}",
    "",
    "function kaptcha_random_bg() {",
    "\t// plain white background, as requested — just the base color, with a",
    "\t// very faint warm-white jitter so it isn't a perfectly flat fill",
    "\treturn [",
    "\t\t255,",
    "\t\t255,",
    "\t\t255,",
    "\t];",
    "}",
    "",
    "function kaptcha_generate_image($text) {",
    "\t$width = 130;",
    "\t$height = 58;",
    "\t$img = imagecreatetruecolor($width, $height);",
    "",
    "\t[$bg_r, $bg_g, $bg_b] = kaptcha_random_bg();",
    "\t$bg = imagecolorallocate($img, $bg_r, $bg_g, $bg_b);",
    "\timagefilledrectangle($img, 0, 0, $width, $height, $bg);",
    "",
    "\t// faint speckle texture — light gray, subtle against the white background",
    "\tfor ($i = 0; $i < 250; $i++) {",
    "\t\t$shade = mt_rand(225, 245);",
    "\t\t$c = imagecolorallocate($img, $shade, $shade, $shade);",
    "\t\timagesetpixel($img, mt_rand(0, $width - 1), mt_rand(0, $height - 1), $c);",
    "\t}",
    "",
    "\t// a handful of squiggly gray noise lines, visible but not overpowering",
    "\tfor ($i = 0; $i < 4; $i++) {",
    "\t\t$shade = mt_rand(170, 200);",
    "\t\t$lc = imagecolorallocate($img, $shade, $shade, $shade);",
    "\t\timagesetthickness($img, 1);",
    "\t\timageline(",
    "\t\t\t$img,",
    "\t\t\tmt_rand(0, $width), mt_rand(0, $height),",
    "\t\t\tmt_rand(0, $width), mt_rand(0, $height),",
    "\t\t\t$lc",
    "\t\t);",
    "\t}",
    "",
    "\t$fonts = KAPTCHA_FONTS;",
    "",
    "\t// dark, high-contrast, per-character color palette (readable on white)",
    "\t$textPalette = [",
    "\t\t[20, 20, 20],    // near-black",
    "\t\t[30, 30, 90],    // dark navy",
    "\t\t[90, 20, 20],    // dark maroon",
    "\t\t[20, 70, 30],    // dark green",
    "\t\t[50, 50, 50],    // charcoal",
    "\t];",
    "",
    "\t// pick per-character rendering params up front so we can lay them out",
    "\t$chars = [];",
    "\t$totalWidth = 0;",
    "\tforeach (str_split($text) as $ch) {",
    "\t\t$fontInfo = $fonts[array_rand($fonts)];",
    "\t\t$size = mt_rand(20, 28);",
    "\t\t$angle = mt_rand(-20, 20);",
    "\t\t$displayCh = (mt_rand(0, 1) === 0) ? strtoupper($ch) : strtolower($ch);",
    "\t\t$color = $textPalette[array_rand($textPalette)];",
    "",
    "\t\t$bbox = imagettfbbox($size, 0, $fontInfo['file'], $displayCh);",
    "\t\t$cw = $bbox[2] - $bbox[0];",
    "",
    "\t\t$chars[] = [",
    "\t\t\t'ch' => $displayCh,",
    "\t\t\t'font' => $fontInfo['file'],",
    "\t\t\t'weight' => $fontInfo['weight'],",
    "\t\t\t'size' => $size,",
    "\t\t\t'angle' => $angle,",
    "\t\t\t'color' => $color,",
    "\t\t\t'width' => $cw,",
    "\t\t];",
    "\t\t$totalWidth += $cw + mt_rand(2, 6);",
    "\t}",
    "",
    "\t// if the randomized sizes overflow the canvas, scale font sizes down",
    "\t// slightly rather than letting characters clip or run off the edge",
    "\t$available = $width - 10;",
    "\tif ($totalWidth > $available) {",
    "\t\t$scale = $available / $totalWidth;",
    "\t\tforeach ($chars as &$c) {",
    "\t\t\t$c['size'] = max(14, (int)round($c['size'] * $scale));",
    "\t\t\t$c['width'] = (int)round($c['width'] * $scale);",
    "\t\t}",
    "\t\tunset($c);",
    "\t\t$totalWidth = (int)round($totalWidth * $scale);",
    "\t}",
    "",
    "\t$shadowColor = imagecolorallocate($img, 210, 210, 210);",
    "",
    "\t$x = max(4, (int)(($width - $totalWidth) / 2));",
    "\tforeach ($chars as $c) {",
    "\t\t$baseline = (int)($height / 2) + (int)($c['size'] / 3) + mt_rand(-4, 4);",
    "",
    "\t\t// drop shadow: same glyph, offset, drawn first",
    "\t\timagettftext($img, $c['size'], $c['angle'], $x + 2, $baseline + 2, $shadowColor, $c['font'], $c['ch']);",
    "",
    "\t\t$textColor = imagecolorallocate($img, $c['color'][0], $c['color'][1], $c['color'][2]);",
    "\t\timagettftext($img, $c['size'], $c['angle'], $x, $baseline, $textColor, $c['font'], $c['ch']);",
    "",
    "\t\t$x += $c['width'] + mt_rand(2, 6);",
    "\t}",
    "",
    "\t// a light dusting of distortion dots on top, kept subtle on white",
    "\tfor ($i = 0; $i < 60; $i++) {",
    "\t\t$shade = mt_rand(180, 220);",
    "\t\t$c = imagecolorallocate($img, $shade, $shade, $shade);",
    "\t\timagesetpixel($img, mt_rand(0, $width - 1), mt_rand(0, $height - 1), $c);",
    "\t}",
    "",
    "\t// border drawn into the bitmap itself (in addition to any CSS border)",
    "\t$borderColor = imagecolorallocate($img, 150, 150, 150);",
    "\timagerectangle($img, 0, 0, $width - 1, $height - 1, $borderColor);",
    "",
    "\treturn $img;",
    "}",
    "",
    "/**",
    " * Renders the entire widget iframe's content in one document: the text",
    " * challenge image, [Reload] (reloads this whole frame — both challenges",
    " * together, since they're one record now), and the slider challenge",
    " * (prompt + 5 clickable points). This is the ONLY thing that generates",
    " * challenges (see mode=widget below); mode=image and mode=slider_set",
    " * just read/update the record this created and re-render this same",
    " * function around it.",
    " *",
    " * Each slider point is a plain link to ?mode=slider_set&point=N — no",
    " * live drag handle without JS, so picking a point is the no-JS",
    " * equivalent of dragging a slider to it. Clicking one re-requests this",
    " * same document (via this iframe's own name) with the pick recorded.",
    " *",
    " * @param string $cookie This challenge's identifier. Threaded through",
    " *        explicitly (not read from $_COOKIE here) because this",
    " *        document itself may end up baked into a statically built page",
    " *        — see the mode=widget comment for why relying on $_COOKIE",
    " *        anywhere in here would be unsafe.",
    " * @param array|null $data The stored record for $cookie (text target,",
    " *        slider numbers/target, slider_selected if picked yet). Null if",
    " *        the cookie is somehow unknown/expired — rendered as a \"reload\"",
    " *        prompt instead of a broken challenge.",
    " * @return string Full standalone HTML document (this is an iframe's",
    " *        entire content, not a fragment glued into the parent page).",
    " */",
    "function kaptcha_widget_frame_html($cookie, $data) {",
    "\t$widget_url = '/inc/captcha/kaptcha/entrypoint.php?mode=widget';",
    "",
    "\t$style =",
    "\t\t\"body{margin:0;padding:2px 3px;background:#fff;font-family:Arial,Helvetica,sans-serif;overflow:hidden;box-sizing:border-box;}\" .",
    "\t\t\"*{box-sizing:border-box;}\" .",
    "\t\t\".ka_row{display:flex;align-items:flex-start;gap:6px;}\" .",
    "\t\t\".ka_img{border:1px solid #999;display:block;width:130px;height:58px;}\" .",
    "\t\t\".ka_btns{font-size:11px;line-height:1.4;}\" .",
    "\t\t\".ka_bracket{color:#880000;}\" .",
    "\t\t\".ka_reload{color:#34345C;text-decoration:underline;}\" .",
    "\t\t\".ka_slider_prompt{font-size:11px;color:#333;white-space:nowrap;margin:4px 0 3px 0;}\" .",
    "\t\t\".ka_slider_prompt b{color:#000;}\" .",
    "\t\t\".ka_slider_status{margin-left:3px;font-weight:bold;}\" .",
    "\t\t\".ka_slider_ok{color:#2e8b2e;}\" .",
    "\t\t\".ka_slider_bad{color:#b00000;}\" .",
    "\t\t\".ka_slider_track{position:relative;height:22px;border-bottom:2px solid #999;display:flex;justify-content:space-between;align-items:flex-end;padding:0 2px;}\" .",
    "\t\t\".ka_slider_point{display:inline-block;min-width:16px;text-align:center;font-size:10px;line-height:16px;padding:0 2px;border:1px solid #999;border-bottom:none;border-radius:3px 3px 0 0;background:#eee;color:#333;text-decoration:none;}\" .",
    "\t\t\".ka_slider_point:hover{background:#ddd;}\" .",
    "\t\t\".ka_slider_point_selected{background:#556;color:#fff;border-color:#334;}\" .",
    "\t\t\".ka_pending{font-size:11px;color:#666;padding-top:6px;}\";",
    "",
    "\tif (!$data || !isset($data['target'], $data['slider_numbers'], $data['slider_target'])) {",
    "\t\treturn",
    "\t\t\t\"<!DOCTYPE html><html><head><meta charset='utf-8'><style>{$style}</style></head><body>\" .",
    "\t\t\t\t\"<div class='ka_pending'>Reload failed — <a class='ka_reload' href='{$widget_url}' target='_self'>try again</a>.</div>\" .",
    "\t\t\t\"</body></html>\";",
    "\t}",
    "",
    "\t$img_url = '/inc/captcha/kaptcha/entrypoint.php?mode=image&cookie=' . urlencode($cookie);",
    "",
    "\t$numbers = $data['slider_numbers'];",
    "\t$target = (int)$data['slider_target'];",
    "\t$selected = isset($data['slider_selected']) ? (int)$data['slider_selected'] : 0;",
    "\t$target_number = $numbers[$target - 1];",
    "",
    "\t$points_html = '';",
    "\tfor ($i = 1; $i <= 5; $i++) {",
    "\t\t$is_selected = ($i === $selected);",
    "\t\t$cls = 'ka_slider_point' . ($is_selected ? ' ka_slider_point_selected' : '');",
    "\t\t$href = '/inc/captcha/kaptcha/entrypoint.php?mode=slider_set&point=' . $i;",
    "\t\t$num = (int)$numbers[$i - 1];",
    "\t\t$points_html .= \"<a href='{$href}' class='{$cls}'>{$num}</a>\";",
    "\t}",
    "",
    "\t$status_html = $selected",
    "\t\t? ($selected === $target",
    "\t\t\t? \"<span class='ka_slider_status ka_slider_ok'>&#10003;</span>\"",
    "\t\t\t: \"<span class='ka_slider_status ka_slider_bad'>&#10007;</span>\")",
    "\t\t: '';",
    "",
    "\treturn",
    "\t\t\"<!DOCTYPE html><html><head><meta charset='utf-8'><style>{$style}</style></head>\" .",
    "\t\t\"<body>\" .",
    "\t\t\t\"<div class='ka_row'>\" .",
    "\t\t\t\t\"<img class='ka_img' src='{$img_url}' alt='Kaptcha'>\" .",
    "\t\t\t\t\"<div class='ka_btns'>\" .",
    "\t\t\t\t\t\"<span class='ka_bracket'>[</span><a class='ka_reload' href='{$widget_url}' target='_self'>Reload</a><span class='ka_bracket'>]</span>\" .",
    "\t\t\t\t\"</div>\" .",
    "\t\t\t\"</div>\" .",
    "\t\t\t\"<div class='ka_slider_prompt'>Click on <b>&quot;{$target_number}&quot;</b> {$status_html}</div>\" .",
    "\t\t\t\"<div class='ka_slider_track'>{$points_html}</div>\" .",
    "\t\t\"</body></html>\";",
    "}",
    "",
    "/**",
    " * Renders the outer <table class='kaptcha'> shell: one iframe (whose",
    " * entire content — text image, [Reload], slider prompt+points — is",
    " * generated by kaptcha_widget_frame_html() via ?mode=widget, see below)",
    " * plus the actual form fields that get submitted with the post:",
    " * captcha_text, and nothing else — the slider's answer isn't a form",
    " * field at all, it's recorded server-side against kaptcha_cookie by the",
    " * mode=slider_set click, and checked at submit time from there (see",
    " * kaptcha_verify_from_post() in post.php).",
    " *",
    " * Does NOT generate any challenge itself, and isn't handed one to",
    " * embed — the board's HTML (index/thread pages) is built once by",
    " * buildIndex()/buildThread() and served as a static file afterwards,",
    " * so baking a specific challenge, cookie, or image into this markup",
    " * would freeze the same captcha for every visitor until the next",
    " * rebuild. Everything challenge-related is deferred to the iframe's own",
    " * live request instead.",
    " *",
    " * Each call gets its own iframe name (random) so multiple widgets on",
    " * one page (e.g. full reply form + quick reply) never target each",
    " * other — though nothing inside the iframe actually targets it by name",
    " * (see kaptcha_widget_frame_html(), which uses target='_self' for its",
    " * own links); the name only need be unique so the browser doesn't",
    " * conflate the frames themselves.",
    " *",
    " * @return string HTML fragment, safe to echo directly (autoescape is off).",
    " */",
    "function kaptcha_widget_html($store_dir) {",
    "\t$frame_name = 'ka_frame_' . bin2hex(random_bytes(6));",
    "\t$widget_url = '/inc/captcha/kaptcha/entrypoint.php?mode=widget';",
    "",
    "\treturn",
    "\t\t\"<table class='kaptcha' cellspacing='3' cellpadding='0'><tbody>\" .",
    "\t\t\t\"<tr>\" .",
    "\t\t\t\t\"<td colspan='2' class='ka_widget_cell'>\" .",
    "\t\t\t\t\t\"<iframe name='{$frame_name}' src='{$widget_url}' width='260' height='120' frameborder='0' scrolling='no' style='display:block;border:0;width:260px;height:120px;'></iframe>\" .",
    "\t\t\t\t\"</td>\" .",
    "\t\t\t\"</tr>\" .",
    "\t\t\t\"<tr>\" .",
    "\t\t\t\t\"<td valign='BOTTOM'>\" .",
    "\t\t\t\t\t\"<input type='text' name='captcha_text' value='' class='ka_input captcha_text' placeholder='Please enter the text above' autocomplete='off'>\" .",
    "\t\t\t\t\"</td>\" .",
    "\t\t\t\t\"<td class='k_btns' valign='TOP'>\" .",
    "\t\t\t\t\t\"<img src='/static/thumb.png' class='ka_brand_img' alt='Kaptcha'>\" .",
    "\t\t\t\t\"</td>\" .",
    "\t\t\t\"</tr>\" .",
    "\t\t\"</tbody></table>\";",
    "}",
    "",
    "// HTTP entrypoint — only runs when called directly via web (not when included by post.php).",
    "if (!defined('TINYBOARD')) {",
    "\t$mode = $_GET['mode'] ?? '';",
    "",
    "\tif ($mode === 'widget') {",
    "\t\t// Single request that generates BOTH challenges (text + slider) at",
    "\t\t// once and returns one HTML document containing both — this is",
    "\t\t// the entire content of the widget's one iframe. Doing it as one",
    "\t\t// document instead of two separate frames (one for the text image,",
    "\t\t// one for the slider) avoids a race: two frames loading in",
    "\t\t// parallel on first render would each need to either agree on one",
    "\t\t// kaptcha_cookie or generate their own, and there's no reliable",
    "\t\t// no-JS way to make two independent frame loads coordinate on",
    "\t\t// which cookie \"wins\" when the browser applies whichever Set-Cookie",
    "\t\t// response header arrives last.",
    "\t\tkaptcha_cleanup($store_dir);",
    "",
    "\t\t$text = kaptcha_random_text(4);",
    "\t\t$cookie = bin2hex(random_bytes(16));",
    "\t\tkaptcha_store($store_dir, $cookie, $text);",
    "",
    "\t\t$slider = kaptcha_slider_generate();",
    "\t\t$data = kaptcha_store_merge($store_dir, $cookie, [",
    "\t\t\t'slider_numbers' => $slider['numbers'],",
    "\t\t\t'slider_target' => $slider['target'],",
    "\t\t]);",
    "",
    "\t\t// The cookie also gets set as a real HTTP cookie (for post.php to",
    "\t\t// read at submit time — see kaptcha_verify_from_post() in",
    "\t\t// post.php), but the image and the slider's [Reload]-equivalent",
    "\t\t// links carry it explicitly in the URL too, since this whole",
    "\t\t// document can itself end up baked into a statically built page",
    "\t\t// (buildIndex()/buildThread()) — a cookie set on THIS response",
    "\t\t// only affects this one request, not future loads of that cached",
    "\t\t// page, so anything inside this document that needs to keep",
    "\t\t// referring to the same challenge (the image src, the slider",
    "\t\t// point links) must carry the cookie value explicitly rather than",
    "\t\t// relying on $_COOKIE.",
    "\t\tsetcookie('kaptcha_cookie', $cookie, [",
    "\t\t\t'expires' => time() + 600,",
    "\t\t\t'path' => '/',",
    "\t\t\t'samesite' => 'Lax',",
    "\t\t]);",
    "",
    "\t\theader('Content-Type: text/html; charset=utf-8');",
    "\t\t// no-store: this document (and everything on it — the image, the",
    "\t\t// number buttons) represents a challenge that's consumed at post",
    "\t\t// time. Without this, a browser could serve this same iframe back",
    "\t\t// out of its cache/bfcache after a failed post — e.g. hitting",
    "\t\t// Back — showing a challenge the server has already forgotten,",
    "\t\t// so a correct-looking answer would fail. Forcing a fresh request",
    "\t\t// here means every post attempt gets a genuinely fresh challenge.",
    "\t\theader('Cache-Control: no-store, no-cache, must-revalidate');",
    "\t\techo kaptcha_widget_frame_html($cookie, $data);",
    "\t\texit;",
    "\t}",
    "",
    "\tif ($mode === 'image') {",
    "\t\t// Plain PNG for a specific, already-known cookie (passed explicitly",
    "\t\t// in the query string rather than read from $_COOKIE — see the",
    "\t\t// mode=widget comment above for why). Regenerating the text image",
    "\t\t// from the already-stored answer, rather than generating a new",
    "\t\t// answer here, keeps this idempotent: reloading the image (via the",
    "\t\t// iframe's own reload, itself just this same URL) doesn't change",
    "\t\t// the expected answer underneath the visitor's slider pick.",
    "\t\t$cookie = preg_replace('/[^a-f0-9]/', '', $_GET['cookie'] ?? '');",
    "\t\t$data = $cookie ? kaptcha_fetch($store_dir, $cookie, false) : null;",
    "",
    "\t\theader('Content-Type: image/png');",
    "\t\theader('Cache-Control: no-store, no-cache, must-revalidate');",
    "",
    "\t\tif (!$data || !isset($data['target'])) {",
    "\t\t\t// Expired/unknown cookie (e.g. this URL cached/reloaded after",
    "\t\t\t// the 5-minute TTL): show a blank placeholder rather than a",
    "\t\t\t// broken image. The visitor needs to reload the whole widget",
    "\t\t\t// frame (its own [Reload] link) to get a fresh challenge.",
    "\t\t\t$img = imagecreatetruecolor(130, 58);",
    "\t\t\t$bg = imagecolorallocate($img, 255, 255, 255);",
    "\t\t\timagefilledrectangle($img, 0, 0, 130, 58, $bg);",
    "\t\t\t$fg = imagecolorallocate($img, 150, 150, 150);",
    "\t\t\timagerectangle($img, 0, 0, 129, 57, $fg);",
    "\t\t\timagepng($img);",
    "\t\t\timagedestroy($img);",
    "\t\t\texit;",
    "\t\t}",
    "",
    "\t\t$img = kaptcha_generate_image($data['target']);",
    "\t\timagepng($img);",
    "\t\timagedestroy($img);",
    "\t\texit;",
    "\t}",
    "",
    "\tif ($mode === 'slider_set') {",
    "\t\t// By the time a point link can be clicked, mode=widget has already",
    "\t\t// run at least once for this frame and set kaptcha_cookie, so",
    "\t\t// there's no first-load race here the way there was for the image",
    "\t\t// — reading it from $_COOKIE is safe.",
    "\t\t$cookie = preg_replace('/[^a-f0-9]/', '', $_COOKIE['kaptcha_cookie'] ?? '');",
    "\t\t$point = (int)($_GET['point'] ?? 0);",
    "",
    "\t\t$data = null;",
    "\t\tif ($cookie && $point >= 1 && $point <= 5) {",
    "\t\t\t$data = kaptcha_store_merge($store_dir, $cookie, ['slider_selected' => $point]);",
    "\t\t} elseif ($cookie) {",
    "\t\t\t$data = kaptcha_fetch($store_dir, $cookie, false);",
    "\t\t}",
    "",
    "\t\theader('Content-Type: text/html; charset=utf-8');",
    "\t\theader('Cache-Control: no-store, no-cache, must-revalidate');",
    "\t\techo kaptcha_widget_frame_html($cookie, $data);",
    "\t\texit;",
    "\t}",
    "",
    "\tif ($mode === 'get_html') {",
    "\t\tkaptcha_cleanup($store_dir);",
    "",
    "\t\t$text = kaptcha_random_text(4);",
    "\t\t$cookie = bin2hex(random_bytes(16));",
    "\t\tkaptcha_store($store_dir, $cookie, $text);",
    "",
    "\t\t$img = kaptcha_generate_image($text);",
    "\t\tob_start();",
    "\t\timagepng($img);",
    "\t\t$png_data = ob_get_clean();",
    "\t\timagedestroy($img);",
    "",
    "\t\t$b64 = base64_encode($png_data);",
    "",
    "\t\theader('Content-Type: application/json');",
    "\t\techo json_encode([",
    "\t\t\t'cookie' => $cookie,",
    "\t\t\t'image'  => 'data:image/png;base64,' . $b64,",
    "\t\t]);",
    "\t\texit;",
    "\t}",
    "",
    "\tif ($mode === 'check') {",
    "\t\theader('Content-Type: text/plain');",
    "\t\t$req = array_merge($_GET, $_POST);",
    "\t\t$cookie = preg_replace('/[^a-f0-9]/', '', $req['cookie'] ?? '');",
    "\t\t$answer = trim($req['text'] ?? '');",
    "\t\t$peek = !empty($req['peek']);",
    "",
    "\t\tif (kaptcha_check_direct($store_dir, $cookie, $answer, !$peek)) {",
    "\t\t\techo '1';",
    "\t\t} else {",
    "\t\t\techo '0';",
    "\t\t}",
    "\t\texit;",
    "\t}",
    "",
    "\thttp_response_code(400);",
    "\theader('Content-Type: application/json');",
    "\techo json_encode(['error' => 'unknown mode']);",
    "\texit;",
    "}",
    "",
])

NEW_ENTRYPOINT = "\n".join([
    "<?php",
    "// Own GD-based text captcha, styled after the \"Kaptcha\" reference screenshot:",
    "// per-character randomized font, size, weight, style, case, and rotation",
    "// on a noisy, randomized-color background.",
    "",
    "$store_dir = __DIR__ . '/../../../tmp/kaptcha/';",
    "if (!is_dir($store_dir)) {",
    "\tmkdir($store_dir, 0700, true);",
    "}",
    "",
    "// Font variants, tagged by family + weight so we can pick weight",
    "// explicitly per character (independent from family/style choice).",
    "define('KAPTCHA_FONTS', [",
    "\t['file' => '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',            'weight' => 'regular'],",
    "\t['file' => '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf',       'weight' => 'bold'],",
    "\t['file' => '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf',        'weight' => 'regular'],",
    "\t['file' => '/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf',   'weight' => 'bold'],",
    "\t['file' => '/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf',           'weight' => 'regular'],",
    "\t['file' => '/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf',      'weight' => 'bold'],",
    "]);",
    "",
    "function kaptcha_store($store_dir, $cookie, $target) {",
    "\t$path = $store_dir . preg_replace('/[^a-f0-9]/', '', $cookie) . '.json';",
    "\tfile_put_contents($path, json_encode(['target' => $target, 'ts' => time()]));",
    "}",
    "",
    "/**",
    " * Merges $fields into the existing stored record for $cookie (creating",
    " * one with the current timestamp if none exists yet), without touching",
    " * fields not present in $fields. Used to attach the slider challenge",
    " * (numbers/target/selection) to the same record as the text challenge,",
    " * keyed by the same kaptcha_cookie, instead of needing a second cookie.",
    " */",
    "function kaptcha_store_merge($store_dir, $cookie, $fields) {",
    "\t$path = $store_dir . preg_replace('/[^a-f0-9]/', '', $cookie) . '.json';",
    "\t$data = file_exists($path) ? (json_decode(file_get_contents($path), true) ?: []) : [];",
    "\tif (!isset($data['ts'])) $data['ts'] = time();",
    "\t$data = array_merge($data, $fields);",
    "\tfile_put_contents($path, json_encode($data));",
    "\treturn $data;",
    "}",
    "",
    "function kaptcha_fetch($store_dir, $cookie, $consume = true) {",
    "\t$path = $store_dir . preg_replace('/[^a-f0-9]/', '', $cookie) . '.json';",
    "\tif (!file_exists($path)) return null;",
    "\t$data = json_decode(file_get_contents($path), true);",
    "\tif ($consume) unlink($path);",
    "\treturn $data;",
    "}",
    "",
    "function kaptcha_cleanup($store_dir) {",
    "\tif (mt_rand(0, 50) !== 0) return;",
    "\tforeach (glob($store_dir . '*.json') as $f) {",
    "\t\t$data = json_decode(file_get_contents($f), true);",
    "\t\tif ($data && time() - $data['ts'] > 300) unlink($f);",
    "\t}",
    "}",
    "",
    "/**",
    " * Verify a kaptcha answer directly (used from post.php without an HTTP round-trip).",
    " * $consume controls whether the stored answer is deleted after this check —",
    " * pass false for a non-destructive \"peek\" (e.g. the widget's own [Check] button),",
    " * and leave it true for the real check that happens at post time.",
    " */",
    "function kaptcha_check_direct($store_dir, $cookie, $text, $consume = true) {",
    "\t$data = kaptcha_fetch($store_dir, $cookie, $consume);",
    "\tif (!$data) return false;",
    "\tif (time() - $data['ts'] > 300) return false;",
    "\t// case-insensitive: display randomizes case per character, but the",
    "\t// underlying answer is compared case-insensitively for usability",
    "\treturn strtolower($data['target']) === strtolower(trim($text));",
    "}",
    "",
    "/**",
    " * Verify the slider challenge: was the point the visitor picked",
    " * (slider_selected, set by the mode=slider_set click) the same point",
    " * the prompt asked for (slider_target)? Both live in the same stored",
    " * record as the text challenge, keyed by the same cookie, so this does",
    " * NOT consume/delete the record on its own — the text check",
    " * (kaptcha_check_direct) already owns that, and post.php calls this",
    " * first with $consume = false, then calls the text check to actually",
    " * consume the record. If only the slider challenge is in use for a",
    " * given call site, pass $consume = true here instead.",
    " */",
    "function kaptcha_slider_check_direct($store_dir, $cookie, $consume = false) {",
    "\t$data = kaptcha_fetch($store_dir, $cookie, $consume);",
    "\tif (!$data) return false;",
    "\tif (time() - $data['ts'] > 300) return false;",
    "\tif (!isset($data['slider_target'], $data['slider_selected'])) return false;",
    "\treturn (int)$data['slider_target'] === (int)$data['slider_selected'];",
    "}",
    "",
    "function kaptcha_random_text($length = 4) {",
    "\t// avoid ambiguous chars (0/O, 1/l/I)",
    "\t$charset = 'abcdefghjkmnpqrstuvwxyz23456789';",
    "\t$text = '';",
    "\tfor ($i = 0; $i < $length; $i++) {",
    "\t\t$text .= $charset[random_int(0, strlen($charset) - 1)];",
    "\t}",
    "\treturn $text;",
    "}",
    "",
    "/**",
    " * Generates the slider challenge: 5 points, each labeled with a random",
    " * number 1-99 (deliberately NOT in ascending/sorted order — shuffled,",
    " * so the visitor can't just guess \"leftmost is smallest\"), plus which",
    " * of the 5 points (1-indexed) is the correct one to pick.",
    " *",
    " * @return array{numbers: int[5], target: int} target is 1-5, an index",
    " *         into numbers.",
    " */",
    "function kaptcha_slider_generate() {",
    "\t$numbers = [];",
    "\t// keep the 5 numbers distinct so the prompt is unambiguous",
    "\twhile (count($numbers) < 5) {",
    "\t\t$n = random_int(1, 99);",
    "\t\tif (!in_array($n, $numbers, true)) {",
    "\t\t\t$numbers[] = $n;",
    "\t\t}",
    "\t}",
    "\tshuffle($numbers);",
    "\t$target = random_int(1, 5);",
    "\treturn ['numbers' => $numbers, 'target' => $target];",
    "}",
    "",
    "function kaptcha_random_bg() {",
    "\t// plain white background, as requested — just the base color, with a",
    "\t// very faint warm-white jitter so it isn't a perfectly flat fill",
    "\treturn [",
    "\t\t255,",
    "\t\t255,",
    "\t\t255,",
    "\t];",
    "}",
    "",
    "function kaptcha_generate_image($text) {",
    "\t$width = 130;",
    "\t$height = 58;",
    "\t$img = imagecreatetruecolor($width, $height);",
    "",
    "\t[$bg_r, $bg_g, $bg_b] = kaptcha_random_bg();",
    "\t$bg = imagecolorallocate($img, $bg_r, $bg_g, $bg_b);",
    "\timagefilledrectangle($img, 0, 0, $width, $height, $bg);",
    "",
    "\t// faint speckle texture — light gray, subtle against the white background",
    "\tfor ($i = 0; $i < 250; $i++) {",
    "\t\t$shade = mt_rand(225, 245);",
    "\t\t$c = imagecolorallocate($img, $shade, $shade, $shade);",
    "\t\timagesetpixel($img, mt_rand(0, $width - 1), mt_rand(0, $height - 1), $c);",
    "\t}",
    "",
    "\t// a handful of squiggly gray noise lines, visible but not overpowering",
    "\tfor ($i = 0; $i < 4; $i++) {",
    "\t\t$shade = mt_rand(170, 200);",
    "\t\t$lc = imagecolorallocate($img, $shade, $shade, $shade);",
    "\t\timagesetthickness($img, 1);",
    "\t\timageline(",
    "\t\t\t$img,",
    "\t\t\tmt_rand(0, $width), mt_rand(0, $height),",
    "\t\t\tmt_rand(0, $width), mt_rand(0, $height),",
    "\t\t\t$lc",
    "\t\t);",
    "\t}",
    "",
    "\t$fonts = KAPTCHA_FONTS;",
    "",
    "\t// dark, high-contrast, per-character color palette (readable on white)",
    "\t$textPalette = [",
    "\t\t[20, 20, 20],    // near-black",
    "\t\t[30, 30, 90],    // dark navy",
    "\t\t[90, 20, 20],    // dark maroon",
    "\t\t[20, 70, 30],    // dark green",
    "\t\t[50, 50, 50],    // charcoal",
    "\t];",
    "",
    "\t// pick per-character rendering params up front so we can lay them out",
    "\t$chars = [];",
    "\t$totalWidth = 0;",
    "\tforeach (str_split($text) as $ch) {",
    "\t\t$fontInfo = $fonts[array_rand($fonts)];",
    "\t\t$size = mt_rand(20, 28);",
    "\t\t$angle = mt_rand(-20, 20);",
    "\t\t$displayCh = (mt_rand(0, 1) === 0) ? strtoupper($ch) : strtolower($ch);",
    "\t\t$color = $textPalette[array_rand($textPalette)];",
    "",
    "\t\t$bbox = imagettfbbox($size, 0, $fontInfo['file'], $displayCh);",
    "\t\t$cw = $bbox[2] - $bbox[0];",
    "",
    "\t\t$chars[] = [",
    "\t\t\t'ch' => $displayCh,",
    "\t\t\t'font' => $fontInfo['file'],",
    "\t\t\t'weight' => $fontInfo['weight'],",
    "\t\t\t'size' => $size,",
    "\t\t\t'angle' => $angle,",
    "\t\t\t'color' => $color,",
    "\t\t\t'width' => $cw,",
    "\t\t];",
    "\t\t$totalWidth += $cw + mt_rand(2, 6);",
    "\t}",
    "",
    "\t// if the randomized sizes overflow the canvas, scale font sizes down",
    "\t// slightly rather than letting characters clip or run off the edge",
    "\t$available = $width - 10;",
    "\tif ($totalWidth > $available) {",
    "\t\t$scale = $available / $totalWidth;",
    "\t\tforeach ($chars as &$c) {",
    "\t\t\t$c['size'] = max(14, (int)round($c['size'] * $scale));",
    "\t\t\t$c['width'] = (int)round($c['width'] * $scale);",
    "\t\t}",
    "\t\tunset($c);",
    "\t\t$totalWidth = (int)round($totalWidth * $scale);",
    "\t}",
    "",
    "\t$shadowColor = imagecolorallocate($img, 210, 210, 210);",
    "",
    "\t$x = max(4, (int)(($width - $totalWidth) / 2));",
    "\tforeach ($chars as $c) {",
    "\t\t$baseline = (int)($height / 2) + (int)($c['size'] / 3) + mt_rand(-4, 4);",
    "",
    "\t\t// drop shadow: same glyph, offset, drawn first",
    "\t\timagettftext($img, $c['size'], $c['angle'], $x + 2, $baseline + 2, $shadowColor, $c['font'], $c['ch']);",
    "",
    "\t\t$textColor = imagecolorallocate($img, $c['color'][0], $c['color'][1], $c['color'][2]);",
    "\t\timagettftext($img, $c['size'], $c['angle'], $x, $baseline, $textColor, $c['font'], $c['ch']);",
    "",
    "\t\t$x += $c['width'] + mt_rand(2, 6);",
    "\t}",
    "",
    "\t// a light dusting of distortion dots on top, kept subtle on white",
    "\tfor ($i = 0; $i < 60; $i++) {",
    "\t\t$shade = mt_rand(180, 220);",
    "\t\t$c = imagecolorallocate($img, $shade, $shade, $shade);",
    "\t\timagesetpixel($img, mt_rand(0, $width - 1), mt_rand(0, $height - 1), $c);",
    "\t}",
    "",
    "\t// border drawn into the bitmap itself (in addition to any CSS border)",
    "\t$borderColor = imagecolorallocate($img, 150, 150, 150);",
    "\timagerectangle($img, 0, 0, $width - 1, $height - 1, $borderColor);",
    "",
    "\treturn $img;",
    "}",
    "",
    "/**",
    " * Renders the entire widget iframe's content in one document: the text",
    " * challenge image, [Reload] (reloads this whole frame — both challenges",
    " * together, since they're one record now), and the slider challenge",
    " * (prompt + 5 clickable points). This is the ONLY thing that generates",
    " * challenges (see mode=widget below); mode=image and mode=slider_set",
    " * just read/update the record this created and re-render this same",
    " * function around it.",
    " *",
    " * Each slider point is a plain link to ?mode=slider_set&point=N — no",
    " * live drag handle without JS, so picking a point is the no-JS",
    " * equivalent of dragging a slider to it. Clicking one re-requests this",
    " * same document (via this iframe's own name) with the pick recorded.",
    " *",
    " * @param string $cookie This challenge's identifier. Threaded through",
    " *        explicitly (not read from $_COOKIE here) because this",
    " *        document itself may end up baked into a statically built page",
    " *        — see the mode=widget comment for why relying on $_COOKIE",
    " *        anywhere in here would be unsafe.",
    " * @param array|null $data The stored record for $cookie (text target,",
    " *        slider numbers/target, slider_selected if picked yet). Null if",
    " *        the cookie is somehow unknown/expired — rendered as a \"reload\"",
    " *        prompt instead of a broken challenge.",
    " * @return string Full standalone HTML document (this is an iframe's",
    " *        entire content, not a fragment glued into the parent page).",
    " */",
    "function kaptcha_widget_frame_html($cookie, $data) {",
    "\t$widget_url = '/inc/captcha/kaptcha/entrypoint.php?mode=widget';",
    "",
    "\t$style =",
    "\t\t\"body{margin:0;padding:2px 3px;background:#fff;font-family:Arial,Helvetica,sans-serif;overflow:hidden;box-sizing:border-box;}\" .",
    "\t\t\"*{box-sizing:border-box;}\" .",
    "\t\t\".ka_row{display:flex;align-items:flex-start;gap:6px;}\" .",
    "\t\t\".ka_img{border:1px solid #999;display:block;width:130px;height:58px;}\" .",
    "\t\t\".ka_btns{font-size:11px;line-height:1.4;}\" .",
    "\t\t\".ka_bracket{color:#880000;}\" .",
    "\t\t\".ka_reload{color:#34345C;text-decoration:underline;}\" .",
    "\t\t\".ka_slider_prompt{font-size:11px;color:#333;white-space:nowrap;margin:2px 0;}\" .",
    "\t\t\".ka_slider_prompt b{color:#000;}\" .",
    "\t\t\".ka_slider_track{display:flex;justify-content:space-between;gap:3px;}\" .",
    "\t\t\".ka_slider_point{display:inline-block;min-width:20px;text-align:center;font-size:10px;line-height:13px;padding:1px 4px;border:1px solid #999;border-radius:3px;background:#eee;color:#333;text-decoration:none;}\" .",
    "\t\t\".ka_slider_point:hover{background:#ddd;}\" .",
    "\t\t\".ka_slider_point_selected{background:#556;color:#fff;border-color:#334;}\" .",
    "\t\t\".ka_pending{font-size:11px;color:#666;padding-top:6px;}\";",
    "",
    "\tif (!$data || !isset($data['target'], $data['slider_numbers'], $data['slider_target'])) {",
    "\t\treturn",
    "\t\t\t\"<!DOCTYPE html><html><head><meta charset='utf-8'><meta http-equiv='Cache-Control' content='no-store'><style>{$style}</style></head><body>\" .",
    "\t\t\t\t\"<div class='ka_pending'>Reload failed — <a class='ka_reload' href='{$widget_url}' target='_self'>try again</a>.</div>\" .",
    "\t\t\t\"</body></html>\";",
    "\t}",
    "",
    "\t$img_url = '/inc/captcha/kaptcha/entrypoint.php?mode=image&cookie=' . urlencode($cookie);",
    "",
    "\t$numbers = $data['slider_numbers'];",
    "\t$target = (int)$data['slider_target'];",
    "\t$selected = isset($data['slider_selected']) ? (int)$data['slider_selected'] : 0;",
    "\t$target_number = $numbers[$target - 1];",
    "",
    "\t$points_html = '';",
    "\tfor ($i = 1; $i <= 5; $i++) {",
    "\t\t$is_selected = ($i === $selected);",
    "\t\t$cls = 'ka_slider_point' . ($is_selected ? ' ka_slider_point_selected' : '');",
    "\t\t$href = '/inc/captcha/kaptcha/entrypoint.php?mode=slider_set&point=' . $i;",
    "\t\t$num = (int)$numbers[$i - 1];",
    "\t\t$points_html .= \"<a href='{$href}' class='{$cls}'>{$num}</a>\";",
    "\t}",
    "",
    "\treturn",
    "\t\t\"<!DOCTYPE html><html><head><meta charset='utf-8'><meta http-equiv='Cache-Control' content='no-store'><style>{$style}</style></head>\" .",
    "\t\t\"<body>\" .",
    "\t\t\t\"<div class='ka_row'>\" .",
    "\t\t\t\t\"<img class='ka_img' src='{$img_url}' alt='Kaptcha'>\" .",
    "\t\t\t\t\"<div class='ka_btns'>\" .",
    "\t\t\t\t\t\"<span class='ka_bracket'>[</span><a class='ka_reload' href='{$widget_url}' target='_self'>Reload</a><span class='ka_bracket'>]</span>\" .",
    "\t\t\t\t\"</div>\" .",
    "\t\t\t\"</div>\" .",
    "\t\t\t\"<div class='ka_slider_prompt'>Click on <b>&quot;{$target_number}&quot;</b></div>\" .",
    "\t\t\t\"<div class='ka_slider_track'>{$points_html}</div>\" .",
    "\t\t\"</body></html>\";",
    "}",
    "",
    "/**",
    " * Renders the outer <table class='kaptcha'> shell: one iframe (whose",
    " * entire content — text image, [Reload], slider prompt+points — is",
    " * generated by kaptcha_widget_frame_html() via ?mode=widget, see below)",
    " * plus the actual form fields that get submitted with the post:",
    " * captcha_text, and nothing else — the slider's answer isn't a form",
    " * field at all, it's recorded server-side against kaptcha_cookie by the",
    " * mode=slider_set click, and checked at submit time from there (see",
    " * kaptcha_verify_from_post() in post.php).",
    " *",
    " * Does NOT generate any challenge itself, and isn't handed one to",
    " * embed — the board's HTML (index/thread pages) is built once by",
    " * buildIndex()/buildThread() and served as a static file afterwards,",
    " * so baking a specific challenge, cookie, or image into this markup",
    " * would freeze the same captcha for every visitor until the next",
    " * rebuild. Everything challenge-related is deferred to the iframe's own",
    " * live request instead.",
    " *",
    " * Each call gets its own iframe name (random) so multiple widgets on",
    " * one page (e.g. full reply form + quick reply) never target each",
    " * other — though nothing inside the iframe actually targets it by name",
    " * (see kaptcha_widget_frame_html(), which uses target='_self' for its",
    " * own links); the name only need be unique so the browser doesn't",
    " * conflate the frames themselves.",
    " *",
    " * @return string HTML fragment, safe to echo directly (autoescape is off).",
    " */",
    "function kaptcha_widget_html($store_dir) {",
    "\t$frame_name = 'ka_frame_' . bin2hex(random_bytes(6));",
    "\t$widget_url = '/inc/captcha/kaptcha/entrypoint.php?mode=widget';",
    "",
    "\treturn",
    "\t\t\"<table class='kaptcha' cellspacing='3' cellpadding='0'><tbody>\" .",
    "\t\t\t\"<tr>\" .",
    "\t\t\t\t\"<td colspan='2' class='ka_widget_cell'>\" .",
    "\t\t\t\t\t\"<iframe name='{$frame_name}' src='{$widget_url}' width='260' height='100' frameborder='0' scrolling='no' style='display:block;border:0;width:260px;height:100px;'></iframe>\" .",
    "\t\t\t\t\"</td>\" .",
    "\t\t\t\"</tr>\" .",
    "\t\t\t\"<tr>\" .",
    "\t\t\t\t\"<td valign='BOTTOM'>\" .",
    "\t\t\t\t\t\"<input type='text' name='captcha_text' value='' class='ka_input captcha_text' placeholder='Please enter the text above' autocomplete='off'>\" .",
    "\t\t\t\t\"</td>\" .",
    "\t\t\t\t\"<td class='k_btns' valign='TOP'>\" .",
    "\t\t\t\t\t\"<img src='/static/thumb.png' class='ka_brand_img' alt='Kaptcha'>\" .",
    "\t\t\t\t\"</td>\" .",
    "\t\t\t\"</tr>\" .",
    "\t\t\"</tbody></table>\";",
    "}",
    "",
    "// HTTP entrypoint — only runs when called directly via web (not when included by post.php).",
    "if (!defined('TINYBOARD')) {",
    "\t$mode = $_GET['mode'] ?? '';",
    "",
    "\tif ($mode === 'widget') {",
    "\t\t// Single request that generates BOTH challenges (text + slider) at",
    "\t\t// once and returns one HTML document containing both — this is",
    "\t\t// the entire content of the widget's one iframe. Doing it as one",
    "\t\t// document instead of two separate frames (one for the text image,",
    "\t\t// one for the slider) avoids a race: two frames loading in",
    "\t\t// parallel on first render would each need to either agree on one",
    "\t\t// kaptcha_cookie or generate their own, and there's no reliable",
    "\t\t// no-JS way to make two independent frame loads coordinate on",
    "\t\t// which cookie \"wins\" when the browser applies whichever Set-Cookie",
    "\t\t// response header arrives last.",
    "\t\tkaptcha_cleanup($store_dir);",
    "",
    "\t\t$text = kaptcha_random_text(4);",
    "\t\t$cookie = bin2hex(random_bytes(16));",
    "\t\tkaptcha_store($store_dir, $cookie, $text);",
    "",
    "\t\t$slider = kaptcha_slider_generate();",
    "\t\t$data = kaptcha_store_merge($store_dir, $cookie, [",
    "\t\t\t'slider_numbers' => $slider['numbers'],",
    "\t\t\t'slider_target' => $slider['target'],",
    "\t\t]);",
    "",
    "\t\t// The cookie also gets set as a real HTTP cookie (for post.php to",
    "\t\t// read at submit time — see kaptcha_verify_from_post() in",
    "\t\t// post.php), but the image and the slider's [Reload]-equivalent",
    "\t\t// links carry it explicitly in the URL too, since this whole",
    "\t\t// document can itself end up baked into a statically built page",
    "\t\t// (buildIndex()/buildThread()) — a cookie set on THIS response",
    "\t\t// only affects this one request, not future loads of that cached",
    "\t\t// page, so anything inside this document that needs to keep",
    "\t\t// referring to the same challenge (the image src, the slider",
    "\t\t// point links) must carry the cookie value explicitly rather than",
    "\t\t// relying on $_COOKIE.",
    "\t\tsetcookie('kaptcha_cookie', $cookie, [",
    "\t\t\t'expires' => time() + 600,",
    "\t\t\t'path' => '/',",
    "\t\t\t'samesite' => 'Lax',",
    "\t\t]);",
    "",
    "\t\theader('Content-Type: text/html; charset=utf-8');",
    "\t\t// no-store: this document (and everything on it — the image, the",
    "\t\t// number buttons) represents a challenge that's consumed at post",
    "\t\t// time. Without this, a browser could serve this same iframe back",
    "\t\t// out of its cache/bfcache after a failed post — e.g. hitting",
    "\t\t// Back — showing a challenge the server has already forgotten,",
    "\t\t// so a correct-looking answer would fail. Forcing a fresh request",
    "\t\t// here means every post attempt gets a genuinely fresh challenge.",
    "\t\theader('Cache-Control: no-store, no-cache, must-revalidate');",
    "\t\techo kaptcha_widget_frame_html($cookie, $data);",
    "\t\texit;",
    "\t}",
    "",
    "\tif ($mode === 'image') {",
    "\t\t// Plain PNG for a specific, already-known cookie (passed explicitly",
    "\t\t// in the query string rather than read from $_COOKIE — see the",
    "\t\t// mode=widget comment above for why). Regenerating the text image",
    "\t\t// from the already-stored answer, rather than generating a new",
    "\t\t// answer here, keeps this idempotent: reloading the image (via the",
    "\t\t// iframe's own reload, itself just this same URL) doesn't change",
    "\t\t// the expected answer underneath the visitor's slider pick.",
    "\t\t$cookie = preg_replace('/[^a-f0-9]/', '', $_GET['cookie'] ?? '');",
    "\t\t$data = $cookie ? kaptcha_fetch($store_dir, $cookie, false) : null;",
    "",
    "\t\theader('Content-Type: image/png');",
    "\t\theader('Cache-Control: no-store, no-cache, must-revalidate');",
    "",
    "\t\tif (!$data || !isset($data['target'])) {",
    "\t\t\t// Expired/unknown cookie (e.g. this URL cached/reloaded after",
    "\t\t\t// the 5-minute TTL): show a blank placeholder rather than a",
    "\t\t\t// broken image. The visitor needs to reload the whole widget",
    "\t\t\t// frame (its own [Reload] link) to get a fresh challenge.",
    "\t\t\t$img = imagecreatetruecolor(130, 58);",
    "\t\t\t$bg = imagecolorallocate($img, 255, 255, 255);",
    "\t\t\timagefilledrectangle($img, 0, 0, 130, 58, $bg);",
    "\t\t\t$fg = imagecolorallocate($img, 150, 150, 150);",
    "\t\t\timagerectangle($img, 0, 0, 129, 57, $fg);",
    "\t\t\timagepng($img);",
    "\t\t\timagedestroy($img);",
    "\t\t\texit;",
    "\t\t}",
    "",
    "\t\t$img = kaptcha_generate_image($data['target']);",
    "\t\timagepng($img);",
    "\t\timagedestroy($img);",
    "\t\texit;",
    "\t}",
    "",
    "\tif ($mode === 'slider_set') {",
    "\t\t// By the time a point link can be clicked, mode=widget has already",
    "\t\t// run at least once for this frame and set kaptcha_cookie, so",
    "\t\t// there's no first-load race here the way there was for the image",
    "\t\t// — reading it from $_COOKIE is safe.",
    "\t\t$cookie = preg_replace('/[^a-f0-9]/', '', $_COOKIE['kaptcha_cookie'] ?? '');",
    "\t\t$point = (int)($_GET['point'] ?? 0);",
    "",
    "\t\t$data = null;",
    "\t\tif ($cookie && $point >= 1 && $point <= 5) {",
    "\t\t\t$data = kaptcha_store_merge($store_dir, $cookie, ['slider_selected' => $point]);",
    "\t\t} elseif ($cookie) {",
    "\t\t\t$data = kaptcha_fetch($store_dir, $cookie, false);",
    "\t\t}",
    "",
    "\t\theader('Content-Type: text/html; charset=utf-8');",
    "\t\theader('Cache-Control: no-store, no-cache, must-revalidate');",
    "\t\techo kaptcha_widget_frame_html($cookie, $data);",
    "\t\texit;",
    "\t}",
    "",
    "\tif ($mode === 'get_html') {",
    "\t\tkaptcha_cleanup($store_dir);",
    "",
    "\t\t$text = kaptcha_random_text(4);",
    "\t\t$cookie = bin2hex(random_bytes(16));",
    "\t\tkaptcha_store($store_dir, $cookie, $text);",
    "",
    "\t\t$img = kaptcha_generate_image($text);",
    "\t\tob_start();",
    "\t\timagepng($img);",
    "\t\t$png_data = ob_get_clean();",
    "\t\timagedestroy($img);",
    "",
    "\t\t$b64 = base64_encode($png_data);",
    "",
    "\t\theader('Content-Type: application/json');",
    "\t\techo json_encode([",
    "\t\t\t'cookie' => $cookie,",
    "\t\t\t'image'  => 'data:image/png;base64,' . $b64,",
    "\t\t]);",
    "\t\texit;",
    "\t}",
    "",
    "\tif ($mode === 'check') {",
    "\t\theader('Content-Type: text/plain');",
    "\t\t$req = array_merge($_GET, $_POST);",
    "\t\t$cookie = preg_replace('/[^a-f0-9]/', '', $req['cookie'] ?? '');",
    "\t\t$answer = trim($req['text'] ?? '');",
    "\t\t$peek = !empty($req['peek']);",
    "",
    "\t\tif (kaptcha_check_direct($store_dir, $cookie, $answer, !$peek)) {",
    "\t\t\techo '1';",
    "\t\t} else {",
    "\t\t\techo '0';",
    "\t\t}",
    "\t\texit;",
    "\t}",
    "",
    "\thttp_response_code(400);",
    "\theader('Content-Type: application/json');",
    "\techo json_encode(['error' => 'unknown mode']);",
    "\texit;",
    "}",
    "",
])

POST_OLD = "\n".join([
    "if (strpos($provider_check, 'kaptcha/entrypoint.php') !== false) {",
    "require_once __DIR__ . '/inc/captcha/kaptcha/entrypoint.php';",
    "$store_dir = __DIR__ . '/tmp/kaptcha/';",
    "$slider_data = kaptcha_fetch($store_dir, $cookie, false);",
    "if ($slider_data && isset($slider_data['slider_target']) && !kaptcha_slider_check_direct($store_dir, $cookie, false)) {",
    "return '0';",
    "}",
    "return kaptcha_check_direct($store_dir, $cookie, $text) ? '1' : '0';",
    "}",
])

POST_NEW = "\n".join([
    "if (strpos($provider_check, 'kaptcha/entrypoint.php') !== false) {",
    "require_once __DIR__ . '/inc/captcha/kaptcha/entrypoint.php';",
    "$store_dir = __DIR__ . '/tmp/kaptcha/';",
    "// Slider challenge (drag-to-point) lives in the same stored record as",
    "// the text challenge, under the same cookie. Check it first without",
    "// consuming the record, then check + consume the text answer — both",
    "// must pass. If the slider hasn't been generated for this record yet",
    "// (e.g. a very old form that predates the slider), skip it rather than",
    "// failing every submission.",
    "$slider_data = kaptcha_fetch($store_dir, $cookie, false);",
    "if ($slider_data && isset($slider_data['slider_target']) && !kaptcha_slider_check_direct($store_dir, $cookie, false)) {",
    "return '0';",
    "}",
    "return kaptcha_check_direct($store_dir, $cookie, $text) ? '1' : '0';",
    "}",
])

CSS_OLD = "\n".join([
    ".kaptcha .ka_challenge img,",
    ".kaptcha .ka_challenge iframe {",
    "\tdisplay: block !important;",
    "\tfloat: none !important;",
    "\tmargin: 0 !important;",
    "\tpadding: 0 !important;",
    "\tborder: 1px solid #999 !important;",
    "\tborder-radius: 0 !important;",
    "\tbox-shadow: none !important;",
    "\tbackground: #fff !important;",
    "\tmax-width: none !important;",
    "}",
])

CSS_NEW = "\n".join([
    ".kaptcha .ka_widget_cell iframe {",
    "\tdisplay: block !important;",
    "\tfloat: none !important;",
    "\tmargin: 0 !important;",
    "\tpadding: 0 !important;",
    "\tborder: 1px solid #999 !important;",
    "\tborder-radius: 0 !important;",
    "\tbox-shadow: none !important;",
    "\tbackground: #fff !important;",
    "\tmax-width: none !important;",
    "}",
])


text_patches = [
    {"file": "post.php", "old": POST_OLD, "new": POST_NEW},
    {"file": "stylesheets/style.css", "old": CSS_OLD, "new": CSS_NEW},
]


def apply_whole_file_patch(root, relpath, old_content, new_content):
    path = f"{root}/{relpath}"
    try:
        with open(path, "r", encoding="utf-8") as fh:
            content = fh.read()
    except FileNotFoundError:
        print(f"[FAIL] {relpath}: file not found")
        return False

    if content == new_content:
        print(f"[SKIP] {relpath}: already patched")
        return True

    if content != old_content:
        print(f"[FAIL] {relpath}: file doesn't match the expected pre-patch content.")
        print(f"       Paste the current `cat` output back so a fresh patch can be")
        print(f"       built against it, rather than guessing.")
        return False

    with open(path, "w", encoding="utf-8") as fh:
        fh.write(new_content)
    print(f"[OK]   {relpath}: patched (whole file)")
    return True


def apply_text_patch(root, p):
    path = f"{root}/{p['file']}"
    try:
        with open(path, "r", encoding="utf-8") as fh:
            content = fh.read()
    except FileNotFoundError:
        print(f"[FAIL] {p['file']}: file not found")
        return False

    if p["new"] in content:
        print(f"[SKIP] {p['file']}: already patched")
        return True

    count = content.count(p["old"])
    if count == 0:
        print(f"[FAIL] {p['file']}: expected old text not found")
        return False
    if count > 1:
        print(f"[FAIL] {p['file']}: old text matched {count} times, expected exactly 1")
        return False

    content = content.replace(p["old"], p["new"], 1)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    print(f"[OK]   {p['file']}: patched")
    return True


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else SITE_ROOT
    ok = True
    ok = apply_whole_file_patch(root, "inc/captcha/kaptcha/entrypoint.php", OLD_ENTRYPOINT, NEW_ENTRYPOINT) and ok
    for p in text_patches:
        ok = apply_text_patch(root, p) and ok
    if not ok:
        print("\nOne or more patches failed.")
        sys.exit(1)
    print("\nAll patches applied.")


if __name__ == "__main__":
    main()
